apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userapp-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thgtvcaptain/GoGrpcRestApp.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: managementapp

  syncPolicy:
    syncOptions:
    -  CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
